[package]
name = "todo"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = "1.3.59"
poem-grpc = "0.2.25"
prost = "0.12.3"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

[build-dependencies]
poem-grpc-build = "0.2.23"
